# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
julia:
  - 1.5
os:
  - osx
  - linux
branches:
  only:
    - master
notifications:
  email: false
jobs:
  include:
    - stage: "Documentation"
      os: linux
      julia: 1.5
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
    - stage: "Code coverage"
      julia: 1.5
      os: linux
      script:
        - julia -e 'using Pkg;
          Pkg.build(); Pkg.test(coverage=true);
          import Circuitscape; cd(joinpath(dirname(pathof(Circuitscape)),".."));
          Pkg.add("Coverage");
          using Coverage;
          Codecov.submit(Codecov.process_folder())'