# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
julia:
  - 1.0
os:
  - linux
branches:
  only:
    - master
notifications:
  email: false
after_success:
  - julia -e 'using Pkg;
              Pkg.add("Coverage");
              using Coverage;
              Coveralls.submit(Coveralls.process_folder())'
