using IniFile

immutable Config
    version::VersionNumber
    connect_four_neighbors::Bool
    connect_four_neighbors_only::Bool
    connect_using_avg_resistances::Bool
    use_polygons::Bool
    polygon_file::String
    source_file::String
    ground_file::String
    ground_file_is_resistances::Bool
    use_unit_currents::Bool
    use_direct_grounds::Bool
    remove_src_or_gnd::Symbol
    mask_file::String
    use_mask::Bool
    preemptive_memory_release::Bool
    low_memory_mode: False,
    parallelize::False
    max_parallel::Int
    print_timings::Bool
    print_rusages::Bool
    solver::Symbol
    use_variable_source_strengths::Bool
    variable_source_file::String
    set_null_currents_to_nodata::Bool
    output_file::String
    write_cum_cur_map_only::Bool
    log_transform_maps::Bool
    write_max_cur_maps::Bool
    compress_grids::Bool
    set_null_voltages_to_nodata::Bool
    set_focal_node_currents_to_zero::Bool
    write_volt_maps::Bool
    write_cur_maps::Bool
    habitat_map_is_resistances::Bool
    habitat_file::String
    scenario::Symbol
    data_type::Symbol
    use_included_pairs::Bool
    included_pairs_file::String
    point_file::String
    use_reclass_table::Bool
    reclass_file::String
    profiler_log_file::String
    log_file::String
    log_level::Symbol
    screenprint_log::Bool
end 
